[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ApkPatcherX"
dynamic = ["version"]
authors = [
  { name = "RK_TECHNO_INDIA", email = "TechnoIndian786@gmail.com" }
]

description = "Smali Patcher ( Bypass 𒁍 SSL & Flutter SSL, VPN, USB Debugging, Screen Restrict, One Device Login, Spoof Info & Package Detection, Ads, AES Logs Inject, TG Patch, Pine HooK )"

license = { text = "MIT" }
readme = "README.md"

requires-python = ">=3.10"

dependencies = [
  "requests",
  "r2pipe",
  "asn1crypto",
  "multiprocess",
  "python-telegram-bot>=22,<23"
]

keywords = ["ApkPatcher"]

classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]

[project.scripts]
ApkPatcher = "ApkPatcher.APK_PATCHER:RK_Techno_IND"
apkpatcher = "ApkPatcher.APK_PATCHER:RK_Techno_IND"

[tool.setuptools]
include-package-data = true

packages.find = {}

package-data = { ApkPatcher = [
  "Utils/Files/AES.smali",
  "Utils/Files/Algorithm.dex",
  "Utils/Files/Hook.smali",
  "Utils/Files/lib_Pairip_CoreX.so",
  "Utils/Pine/config.json",
  "Utils/Pine/libpine32",
  "Utils/Pine/libpine64",
  "Utils/Pine/loader.dex"
] }


[project.urls]
Homepage = "https://github.com/TechnoIndian/ApkPatcher"
Repository = "https://github.com/khan23153/Apkpatching.git"
Issues = "https://github.com/khan23153/Apkpatching/issues"

[tool.setuptools.dynamic]
version = { file = "VERSION" }
